### ISSUE TITLE
Discontinued gages

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/FIM#115]
there will be some gages (on the live mapper) in Kansas that will be discontinued. i will need to get those off of live mapper. that means those will exist in review mapper only. do you see any reasons to take these off of review mapper too; ie delete them from the DB? other than storage issues, i would be ok with leaving these on the review mapper. maybe we need to add a "discontinued" field in the "sites" FC? to keep track of these? any suggestions?

**Comment by HansVraga** [comment]
@mhkim01 anything from the Kansas rep?

**Comment by mhkim01** [comment]
@HansVraga nope, not yet. I think we can close this one until KS gets back to us.
