### ISSUE TITLE
Update explanation language when depth grids are shown

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FIM#117]
currently - look up IWRSS specifications for better language
![image](https://cloud.githubusercontent.com/assets/12058013/19455499/321707ca-948b-11e6-869d-0ecdeeaee98c.png)

**Comment by njestes** [comment]
![image_10](https://user-images.githubusercontent.com/5325440/32390343-3fbd9c2c-c08b-11e7-8a01-fc1fe13e8d68.png)
