### ISSUE TITLE
review mapper error messages

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/FIM#119]
I get these errors when I start up the review mapper.

![image](https://cloud.githubusercontent.com/assets/15948427/22072576/c85dfad0-dd70-11e6-8f2c-d01abd30ea3a.png)

![image](https://cloud.githubusercontent.com/assets/15948427/22072593/d31b8960-dd70-11e6-9942-082fafa7e658.png)

**Comment by mhkim01** [comment]
Hey, I got a note from MOWSC that they are releasing preliminary results of recent flooding at Meramec River as FIMs to the cooperators in a week or so using the review mapper. Would it be possible to fix these error messages before then?

**Comment by njestes** [comment]
Should be all set now. Had yet to update the review URLs to https.

**Comment by mhkim01** [comment]
Both public and review mapper (http and https) are have same error message issues now.

**Comment by njestes** [comment]
@HansVraga @mhkim01 Looks like the noaa/nws services are down. This file isn't loading...

https://idpgis.ncep.noaa.gov/crossdomain.xml

So, we're getting security errors when trying to access these services

Not sure who to contact about this

**Comment by njestes** [comment]
@HansVraga @mhkim01 I heard back from NOAA and they added the crossdomain file. Looks like it's working now as long as you load the mapper with https. So, we should redirect to https if a user loads it with http only. I'll ask SysOps about this and close this when it is resolved.
