### ISSUE TITLE
Resolve Nick's printing issue so we can move forward with Prod instances

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FIM#124]
This may just be for FIM so not relevant to the FWS bizness

**Comment by aaronstephenson** [comment]
Anything new here? @HansVraga @BlakeDraper

**Comment by njestes** [comment]
nothing new. back burner

**Comment by DanielJBeckman** [comment]
Note: This concerns some custom code written to customize print products that does not properly work in newer versions of ArcGIS Server.

**Comment by aaronstephenson** [comment]
Well, no, the code in question is not a bridge, but simply a printing utility that Nick wrote for a specific version of ArcGIS Server. It doesn't work on newer versions of AGS. We don't know why and haven't had a chance to investigate it.

**Comment by njestes** [comment]
I have found a new path to replacing the existing print utility, so won't be needing sysops interaction or help at this point. Will create new more specific issues as needed.
