### ISSUE TITLE
streamgage symbol not showing on print product

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/FIM#126]
![image](https://cloud.githubusercontent.com/assets/15948427/25639304/6bd3f004-2f59-11e7-83a6-97ed620a0806.png)

**Comment by njestes** [comment]
@mhkim01 I'm pretty sure this is due to having an old sites layer on the FIM machines where the print is happening. Can you update the db on the FIM to be same as the db on the jump server. That should do the trick. Let me know if you want to look over it together.
