### ISSUE TITLE
water depth pop-up bubble not working

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/FIM#127]
only for some of the new maps I loaded, this function is not working in the review mapper. as far as i can tell, grids are loaded as usual and it should be working but it's not.

**Comment by mhkim01** [comment]
See Noblesville, IN, Fenton, MO, and Jasper, IN.

**Comment by njestes** [comment]
I hadn't yet updated the references to the grid services for the Review mapper. I was still pointing to the test grid services. Should be good to go now.
