### ISSUE TITLE
HAZUS tab not functioning for any of FIM sites

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/FIM#128]
There used to be bunch of numbers showing static info and damage loss info but now, empty space...

![image](https://cloud.githubusercontent.com/assets/15948427/26741504/a1f80b82-47a7-11e7-9ee8-882a663f4b98.png)

**Comment by mhkim01** [comment]
hey all, users are noticing that the HAZUS tabs are missing from the sites that used to have them. is someone working on the HAZUS tool lately?
![image](https://user-images.githubusercontent.com/15948427/28881065-edc589e8-7774-11e7-9de6-e36b4038e3f2.png)

**Comment by mhkim01** [comment]
also, i cannot remember if we (Marie?) was supposed to send out email to users regarding HAZUS tool being offline?

**Comment by HansVraga** [comment]
Eric, a recent addition to the team, will be working on HAZUS these next two months to restore service.
Not sure about the Marie thing.

**Comment by HansVraga** [comment]
This effort has been abandoned. Unable to locate an older version of the HAZUS database and software required to stand up these services. Future efforts will include outreach to FEMA HAZUS coordinator for alternative methods to access this data. These will be tracked elsewhere.
