### ISSUE TITLE
Flood tool tab not loading for a site.

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/FIM#129]
http://wimcloud.usgs.gov/apps/FIMReview/FloodInundationMapper.html?siteno=01116500

Well, i am stumped. I have checked everything I can think of and I have no idea why Flood tool tab will not load for this particular site. I have checked some others on the review mapper and they are not having this issues.

**Comment by njestes** [comment]
@mhkim01 are you still having this issue? It's working fine for me

**Comment by mhkim01** [comment]
it works fine now
