### ISSUE TITLE
FIM (flash) Redirect to https://

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FIM#133]
Please redirect users who visit http://wimcloud.usgs.gov/* to https://wimcloud.usgs.gov/*

Hit @njestes or @hansvraga up if there are questions

**Comment by aaronstephenson** [comment]
Done. Please verify this works for you.

**Comment by njestes** [comment]
Looks good to me @aaronstephenson . @HansVraga verify for yourself and we can close 'er down.

**Comment by mhkim01** [comment]
works for me too.
