### ISSUE TITLE
New grids_4 service not working?

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/FIM#139]
Valley Park, MO (2-site matrix) is only FIM that's on grids_4 service; The values for depth range does not pop up for this sites. Arnold, MO (also a 2-site matrix) works fine on the grids_3 service. I double check the sites layer attribute table and I believe I entered the values correctly.

**Comment by mhkim01** [comment]
@njestes as of now, all grids_# services have over 1000 grids which is over the max set a while ago? I have more fims to load so I will continue to add these on existing grids_# services unless you tell me otherwise.

**Comment by njestes** [comment]
@mhkim01 I believe this is working now. So far only updated FIMReview. Will wait for confirmation from you that we're good to go and then I'll update the main FIM mapper.
