### ISSUE TITLE
Goshen, OR: NWS flood stage colors are not showing on the flood tools sliders and on the historical flooding tab.

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/FIM#79]
NWS XML file is missing "moderate" level stage value. Could that screw it up?

**Comment by njestes** [comment]
![image_11](https://user-images.githubusercontent.com/5325440/32391038-e687b2c0-c08d-11e7-91b0-62a1212c601a.png)

**Comment by HansVraga** [comment]
@m
